apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tape.fullname" . }}-server
  labels: {{- include "tape.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.serverGsa }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tape.fullname" . }}-reactor
  labels: {{- include "tape.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.reactorGsa }}
  {{- end }}
