// Tape — the wire contract.
//
// A durable-execution substrate for ADK agents. See ../../design-principles/tape.md.
//
// Flexible payloads (model requests/responses, tool args/results, event content,
// state values, compensation payloads) are carried as JSON strings. This keeps
// the contract small and the cross-language SDKs honest: the server treats them
// as opaque blobs; only the agent's own code interprets them.
//
// Every mutating RPC carries (run_id, seq) — or, for BeginEffect, (run_id,
// decision_seq, attempt) — and is idempotent: replaying it returns the recorded
// result instead of acting twice. That is what makes the SDK and the recovery
// loop safe to retry freely.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: tape.proto

package tapepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tape_BeginRun_FullMethodName                  = "/tape.v1.Tape/BeginRun"
	Tape_ResumeRun_FullMethodName                 = "/tape.v1.Tape/ResumeRun"
	Tape_EndRun_FullMethodName                    = "/tape.v1.Tape/EndRun"
	Tape_GetRun_FullMethodName                    = "/tape.v1.Tape/GetRun"
	Tape_ListRunsToRecover_FullMethodName         = "/tape.v1.Tape/ListRunsToRecover"
	Tape_SubscribeRun_FullMethodName              = "/tape.v1.Tape/SubscribeRun"
	Tape_RecordDecision_FullMethodName            = "/tape.v1.Tape/RecordDecision"
	Tape_GetDecision_FullMethodName               = "/tape.v1.Tape/GetDecision"
	Tape_BeginEffect_FullMethodName               = "/tape.v1.Tape/BeginEffect"
	Tape_CompleteEffect_FullMethodName            = "/tape.v1.Tape/CompleteEffect"
	Tape_GetEffect_FullMethodName                 = "/tape.v1.Tape/GetEffect"
	Tape_ReconcileEffect_FullMethodName           = "/tape.v1.Tape/ReconcileEffect"
	Tape_ListEffectsToDispatch_FullMethodName     = "/tape.v1.Tape/ListEffectsToDispatch"
	Tape_ClaimEffectDispatch_FullMethodName       = "/tape.v1.Tape/ClaimEffectDispatch"
	Tape_RecordDispatchAttempt_FullMethodName     = "/tape.v1.Tape/RecordDispatchAttempt"
	Tape_RecordExternalObservation_FullMethodName = "/tape.v1.Tape/RecordExternalObservation"
	Tape_RegisterCompensation_FullMethodName      = "/tape.v1.Tape/RegisterCompensation"
	Tape_ListObligations_FullMethodName           = "/tape.v1.Tape/ListObligations"
	Tape_ResolveObligation_FullMethodName         = "/tape.v1.Tape/ResolveObligation"
	Tape_ListUnresolvedObligations_FullMethodName = "/tape.v1.Tape/ListUnresolvedObligations"
	Tape_ClaimObligation_FullMethodName           = "/tape.v1.Tape/ClaimObligation"
	Tape_RecordObligationAttempt_FullMethodName   = "/tape.v1.Tape/RecordObligationAttempt"
	Tape_SetBudget_FullMethodName                 = "/tape.v1.Tape/SetBudget"
	Tape_AdmitBudget_FullMethodName               = "/tape.v1.Tape/AdmitBudget"
	Tape_ChargeBudget_FullMethodName              = "/tape.v1.Tape/ChargeBudget"
	Tape_AwaitSignal_FullMethodName               = "/tape.v1.Tape/AwaitSignal"
	Tape_SendSignal_FullMethodName                = "/tape.v1.Tape/SendSignal"
	Tape_ListPendingEffects_FullMethodName        = "/tape.v1.Tape/ListPendingEffects"
	Tape_SetTimer_FullMethodName                  = "/tape.v1.Tape/SetTimer"
	Tape_CancelTimer_FullMethodName               = "/tape.v1.Tape/CancelTimer"
	Tape_ListDueTimers_FullMethodName             = "/tape.v1.Tape/ListDueTimers"
	Tape_SubscribeEvents_FullMethodName           = "/tape.v1.Tape/SubscribeEvents"
	Tape_SubscribeBySubject_FullMethodName        = "/tape.v1.Tape/SubscribeBySubject"
	Tape_RegisterReaction_FullMethodName          = "/tape.v1.Tape/RegisterReaction"
	Tape_DeregisterReaction_FullMethodName        = "/tape.v1.Tape/DeregisterReaction"
	Tape_ListReactions_FullMethodName             = "/tape.v1.Tape/ListReactions"
	Tape_ClaimTasks_FullMethodName                = "/tape.v1.Tape/ClaimTasks"
	Tape_CompleteTask_FullMethodName              = "/tape.v1.Tape/CompleteTask"
	Tape_NackTask_FullMethodName                  = "/tape.v1.Tape/NackTask"
	Tape_ListTasks_FullMethodName                 = "/tape.v1.Tape/ListTasks"
	Tape_WriteValue_FullMethodName                = "/tape.v1.Tape/WriteValue"
	Tape_GetValue_FullMethodName                  = "/tape.v1.Tape/GetValue"
	Tape_WatchValue_FullMethodName                = "/tape.v1.Tape/WatchValue"
	Tape_DeleteValue_FullMethodName               = "/tape.v1.Tape/DeleteValue"
	Tape_CreateSession_FullMethodName             = "/tape.v1.Tape/CreateSession"
	Tape_GetSession_FullMethodName                = "/tape.v1.Tape/GetSession"
	Tape_ListSessions_FullMethodName              = "/tape.v1.Tape/ListSessions"
	Tape_DeleteSession_FullMethodName             = "/tape.v1.Tape/DeleteSession"
	Tape_AppendEvent_FullMethodName               = "/tape.v1.Tape/AppendEvent"
)

// TapeClient is the client API for Tape service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TapeClient interface {
	// ── run lifecycle ─────────────────────────────────────────────────────────
	BeginRun(ctx context.Context, in *BeginRunRequest, opts ...grpc.CallOption) (*BeginRunResponse, error)
	ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*ResumeRunResponse, error)
	EndRun(ctx context.Context, in *EndRunRequest, opts ...grpc.CallOption) (*EndRunResponse, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*RunState, error)
	ListRunsToRecover(ctx context.Context, in *ListRunsToRecoverRequest, opts ...grpc.CallOption) (*ListRunsToRecoverResponse, error)
	SubscribeRun(ctx context.Context, in *SubscribeRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JournalEntry], error)
	// ── decision ledger ───────────────────────────────────────────────────────
	RecordDecision(ctx context.Context, in *RecordDecisionRequest, opts ...grpc.CallOption) (*DecisionRecord, error)
	GetDecision(ctx context.Context, in *GetDecisionRequest, opts ...grpc.CallOption) (*GetDecisionResponse, error)
	// ── effect ledger ─────────────────────────────────────────────────────────
	BeginEffect(ctx context.Context, in *BeginEffectRequest, opts ...grpc.CallOption) (*BeginEffectResponse, error)
	CompleteEffect(ctx context.Context, in *CompleteEffectRequest, opts ...grpc.CallOption) (*EffectRecord, error)
	GetEffect(ctx context.Context, in *GetEffectRequest, opts ...grpc.CallOption) (*GetEffectResponse, error)
	ReconcileEffect(ctx context.Context, in *ReconcileEffectRequest, opts ...grpc.CallOption) (*EffectRecord, error)
	// ── outbox dispatch (the GCP-native hardening: for non-idempotent upstreams,
	//
	//	intent and dispatch live in separate processes; the tool body records
	//	intent, the outbox reactor dispatches via a connector, the reconciler
	//	resolves UNKNOWN ambiguity by asking the counterparty) ────────────────
	ListEffectsToDispatch(ctx context.Context, in *ListEffectsToDispatchRequest, opts ...grpc.CallOption) (*ListEffectsToDispatchResponse, error)
	ClaimEffectDispatch(ctx context.Context, in *ClaimEffectDispatchRequest, opts ...grpc.CallOption) (*ClaimEffectDispatchResponse, error)
	RecordDispatchAttempt(ctx context.Context, in *RecordDispatchAttemptRequest, opts ...grpc.CallOption) (*EffectRecord, error)
	RecordExternalObservation(ctx context.Context, in *RecordExternalObservationRequest, opts ...grpc.CallOption) (*EffectRecord, error)
	// ── obligations / compensation ────────────────────────────────────────────
	RegisterCompensation(ctx context.Context, in *RegisterCompensationRequest, opts ...grpc.CallOption) (*ObligationRecord, error)
	ListObligations(ctx context.Context, in *ListObligationsRequest, opts ...grpc.CallOption) (*ListObligationsResponse, error)
	ResolveObligation(ctx context.Context, in *ResolveObligationRequest, opts ...grpc.CallOption) (*ObligationRecord, error)
	// The drainer surface — for the obligations reactor and operator queries.
	ListUnresolvedObligations(ctx context.Context, in *ListUnresolvedObligationsRequest, opts ...grpc.CallOption) (*ListUnresolvedObligationsResponse, error)
	ClaimObligation(ctx context.Context, in *ClaimObligationRequest, opts ...grpc.CallOption) (*ClaimObligationResponse, error)
	RecordObligationAttempt(ctx context.Context, in *RecordObligationAttemptRequest, opts ...grpc.CallOption) (*ObligationRecord, error)
	// ── budget ────────────────────────────────────────────────────────────────
	SetBudget(ctx context.Context, in *SetBudgetRequest, opts ...grpc.CallOption) (*BudgetState, error)
	AdmitBudget(ctx context.Context, in *AdmitBudgetRequest, opts ...grpc.CallOption) (*AdmitBudgetResponse, error)
	ChargeBudget(ctx context.Context, in *ChargeBudgetRequest, opts ...grpc.CallOption) (*BudgetState, error)
	// ── gates / signals ───────────────────────────────────────────────────────
	AwaitSignal(ctx context.Context, in *AwaitSignalRequest, opts ...grpc.CallOption) (*AwaitSignalResponse, error)
	SendSignal(ctx context.Context, in *SendSignalRequest, opts ...grpc.CallOption) (*SendSignalResponse, error)
	// ── reconciliation ────────────────────────────────────────────────────────
	ListPendingEffects(ctx context.Context, in *ListPendingEffectsRequest, opts ...grpc.CallOption) (*ListPendingEffectsResponse, error)
	// ── timers (the delayed-reactor / gate-timeout service) ───────────────────
	SetTimer(ctx context.Context, in *SetTimerRequest, opts ...grpc.CallOption) (*TimerRecord, error)
	CancelTimer(ctx context.Context, in *CancelTimerRequest, opts ...grpc.CallOption) (*CancelTimerResponse, error)
	ListDueTimers(ctx context.Context, in *ListDueTimersRequest, opts ...grpc.CallOption) (*ListDueTimersResponse, error)
	// ── the WAL → reactors feed (cross-run journal tail) ──────────────────────
	// The legacy cross-run journal stream; preserved for back-compat.
	// `SubscribeEventsRequest` now also accepts `from_global_seq` and
	// `subject_pattern`; pass them instead of `from_ts_ms` for new code.
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEntry], error)
	// The subject-routed, global-seq-cursored bus. Path-style subjects with
	// `*` (one segment) / `**` (rest) wildcards; optional CEL predicate.
	SubscribeBySubject(ctx context.Context, in *SubscribeBySubjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEntry], error)
	// ── reactions & tasks (the event-bus surface; see design-principles/tape-event-bus.md) ─
	// Reactions are server-side subscriptions: a subject pattern + optional CEL
	// predicate + a handler kind (agent | task | publish) + back-pressure config.
	// Matching journal entries become `tape_tasks` rows that dispatchers claim,
	// run, and complete/nack.
	RegisterReaction(ctx context.Context, in *Reaction, opts ...grpc.CallOption) (*Reaction, error)
	DeregisterReaction(ctx context.Context, in *DeregisterReactionRequest, opts ...grpc.CallOption) (*DeregisterReactionResponse, error)
	ListReactions(ctx context.Context, in *ListReactionsRequest, opts ...grpc.CallOption) (*ListReactionsResponse, error)
	ClaimTasks(ctx context.Context, in *ClaimTasksRequest, opts ...grpc.CallOption) (*ClaimTasksResponse, error)
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	NackTask(ctx context.Context, in *NackTaskRequest, opts ...grpc.CallOption) (*NackTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// ── reactive key-value store (the "X : X (70 → 90)" surface) ──────────────
	// Coordination through journaled state, not messages (treatise §IX ⑥).
	// Writes are atomic and versioned; WatchValue streams the current value plus
	// every change (with the prior value, so subscribers see the transition).
	WriteValue(ctx context.Context, in *WriteValueRequest, opts ...grpc.CallOption) (*ValueRecord, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	WatchValue(ctx context.Context, in *WatchValueRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ValueEvent], error)
	DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error)
	// ── ADK SessionService shim ───────────────────────────────────────────────
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error)
}

type tapeClient struct {
	cc grpc.ClientConnInterface
}

func NewTapeClient(cc grpc.ClientConnInterface) TapeClient {
	return &tapeClient{cc}
}

func (c *tapeClient) BeginRun(ctx context.Context, in *BeginRunRequest, opts ...grpc.CallOption) (*BeginRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginRunResponse)
	err := c.cc.Invoke(ctx, Tape_BeginRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*ResumeRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRunResponse)
	err := c.cc.Invoke(ctx, Tape_ResumeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) EndRun(ctx context.Context, in *EndRunRequest, opts ...grpc.CallOption) (*EndRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndRunResponse)
	err := c.cc.Invoke(ctx, Tape_EndRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*RunState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunState)
	err := c.cc.Invoke(ctx, Tape_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListRunsToRecover(ctx context.Context, in *ListRunsToRecoverRequest, opts ...grpc.CallOption) (*ListRunsToRecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsToRecoverResponse)
	err := c.cc.Invoke(ctx, Tape_ListRunsToRecover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) SubscribeRun(ctx context.Context, in *SubscribeRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JournalEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tape_ServiceDesc.Streams[0], Tape_SubscribeRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRunRequest, JournalEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_SubscribeRunClient = grpc.ServerStreamingClient[JournalEntry]

func (c *tapeClient) RecordDecision(ctx context.Context, in *RecordDecisionRequest, opts ...grpc.CallOption) (*DecisionRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionRecord)
	err := c.cc.Invoke(ctx, Tape_RecordDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) GetDecision(ctx context.Context, in *GetDecisionRequest, opts ...grpc.CallOption) (*GetDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDecisionResponse)
	err := c.cc.Invoke(ctx, Tape_GetDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) BeginEffect(ctx context.Context, in *BeginEffectRequest, opts ...grpc.CallOption) (*BeginEffectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginEffectResponse)
	err := c.cc.Invoke(ctx, Tape_BeginEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) CompleteEffect(ctx context.Context, in *CompleteEffectRequest, opts ...grpc.CallOption) (*EffectRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectRecord)
	err := c.cc.Invoke(ctx, Tape_CompleteEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) GetEffect(ctx context.Context, in *GetEffectRequest, opts ...grpc.CallOption) (*GetEffectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEffectResponse)
	err := c.cc.Invoke(ctx, Tape_GetEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ReconcileEffect(ctx context.Context, in *ReconcileEffectRequest, opts ...grpc.CallOption) (*EffectRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectRecord)
	err := c.cc.Invoke(ctx, Tape_ReconcileEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListEffectsToDispatch(ctx context.Context, in *ListEffectsToDispatchRequest, opts ...grpc.CallOption) (*ListEffectsToDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEffectsToDispatchResponse)
	err := c.cc.Invoke(ctx, Tape_ListEffectsToDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ClaimEffectDispatch(ctx context.Context, in *ClaimEffectDispatchRequest, opts ...grpc.CallOption) (*ClaimEffectDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimEffectDispatchResponse)
	err := c.cc.Invoke(ctx, Tape_ClaimEffectDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) RecordDispatchAttempt(ctx context.Context, in *RecordDispatchAttemptRequest, opts ...grpc.CallOption) (*EffectRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectRecord)
	err := c.cc.Invoke(ctx, Tape_RecordDispatchAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) RecordExternalObservation(ctx context.Context, in *RecordExternalObservationRequest, opts ...grpc.CallOption) (*EffectRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectRecord)
	err := c.cc.Invoke(ctx, Tape_RecordExternalObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) RegisterCompensation(ctx context.Context, in *RegisterCompensationRequest, opts ...grpc.CallOption) (*ObligationRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObligationRecord)
	err := c.cc.Invoke(ctx, Tape_RegisterCompensation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListObligations(ctx context.Context, in *ListObligationsRequest, opts ...grpc.CallOption) (*ListObligationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObligationsResponse)
	err := c.cc.Invoke(ctx, Tape_ListObligations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ResolveObligation(ctx context.Context, in *ResolveObligationRequest, opts ...grpc.CallOption) (*ObligationRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObligationRecord)
	err := c.cc.Invoke(ctx, Tape_ResolveObligation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListUnresolvedObligations(ctx context.Context, in *ListUnresolvedObligationsRequest, opts ...grpc.CallOption) (*ListUnresolvedObligationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUnresolvedObligationsResponse)
	err := c.cc.Invoke(ctx, Tape_ListUnresolvedObligations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ClaimObligation(ctx context.Context, in *ClaimObligationRequest, opts ...grpc.CallOption) (*ClaimObligationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimObligationResponse)
	err := c.cc.Invoke(ctx, Tape_ClaimObligation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) RecordObligationAttempt(ctx context.Context, in *RecordObligationAttemptRequest, opts ...grpc.CallOption) (*ObligationRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObligationRecord)
	err := c.cc.Invoke(ctx, Tape_RecordObligationAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) SetBudget(ctx context.Context, in *SetBudgetRequest, opts ...grpc.CallOption) (*BudgetState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetState)
	err := c.cc.Invoke(ctx, Tape_SetBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) AdmitBudget(ctx context.Context, in *AdmitBudgetRequest, opts ...grpc.CallOption) (*AdmitBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitBudgetResponse)
	err := c.cc.Invoke(ctx, Tape_AdmitBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ChargeBudget(ctx context.Context, in *ChargeBudgetRequest, opts ...grpc.CallOption) (*BudgetState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetState)
	err := c.cc.Invoke(ctx, Tape_ChargeBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) AwaitSignal(ctx context.Context, in *AwaitSignalRequest, opts ...grpc.CallOption) (*AwaitSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwaitSignalResponse)
	err := c.cc.Invoke(ctx, Tape_AwaitSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) SendSignal(ctx context.Context, in *SendSignalRequest, opts ...grpc.CallOption) (*SendSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSignalResponse)
	err := c.cc.Invoke(ctx, Tape_SendSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListPendingEffects(ctx context.Context, in *ListPendingEffectsRequest, opts ...grpc.CallOption) (*ListPendingEffectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingEffectsResponse)
	err := c.cc.Invoke(ctx, Tape_ListPendingEffects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) SetTimer(ctx context.Context, in *SetTimerRequest, opts ...grpc.CallOption) (*TimerRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimerRecord)
	err := c.cc.Invoke(ctx, Tape_SetTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) CancelTimer(ctx context.Context, in *CancelTimerRequest, opts ...grpc.CallOption) (*CancelTimerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTimerResponse)
	err := c.cc.Invoke(ctx, Tape_CancelTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListDueTimers(ctx context.Context, in *ListDueTimersRequest, opts ...grpc.CallOption) (*ListDueTimersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDueTimersResponse)
	err := c.cc.Invoke(ctx, Tape_ListDueTimers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tape_ServiceDesc.Streams[1], Tape_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, EventEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_SubscribeEventsClient = grpc.ServerStreamingClient[EventEntry]

func (c *tapeClient) SubscribeBySubject(ctx context.Context, in *SubscribeBySubjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tape_ServiceDesc.Streams[2], Tape_SubscribeBySubject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeBySubjectRequest, EventEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_SubscribeBySubjectClient = grpc.ServerStreamingClient[EventEntry]

func (c *tapeClient) RegisterReaction(ctx context.Context, in *Reaction, opts ...grpc.CallOption) (*Reaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reaction)
	err := c.cc.Invoke(ctx, Tape_RegisterReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) DeregisterReaction(ctx context.Context, in *DeregisterReactionRequest, opts ...grpc.CallOption) (*DeregisterReactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterReactionResponse)
	err := c.cc.Invoke(ctx, Tape_DeregisterReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListReactions(ctx context.Context, in *ListReactionsRequest, opts ...grpc.CallOption) (*ListReactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReactionsResponse)
	err := c.cc.Invoke(ctx, Tape_ListReactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ClaimTasks(ctx context.Context, in *ClaimTasksRequest, opts ...grpc.CallOption) (*ClaimTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimTasksResponse)
	err := c.cc.Invoke(ctx, Tape_ClaimTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, Tape_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) NackTask(ctx context.Context, in *NackTaskRequest, opts ...grpc.CallOption) (*NackTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackTaskResponse)
	err := c.cc.Invoke(ctx, Tape_NackTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, Tape_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) WriteValue(ctx context.Context, in *WriteValueRequest, opts ...grpc.CallOption) (*ValueRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValueRecord)
	err := c.cc.Invoke(ctx, Tape_WriteValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, Tape_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) WatchValue(ctx context.Context, in *WatchValueRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ValueEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tape_ServiceDesc.Streams[3], Tape_WatchValue_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchValueRequest, ValueEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_WatchValueClient = grpc.ServerStreamingClient[ValueEvent]

func (c *tapeClient) DeleteValue(ctx context.Context, in *DeleteValueRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteValueResponse)
	err := c.cc.Invoke(ctx, Tape_DeleteValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Tape_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, Tape_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, Tape_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, Tape_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapeClient) AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*AppendEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEventResponse)
	err := c.cc.Invoke(ctx, Tape_AppendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TapeServer is the server API for Tape service.
// All implementations must embed UnimplementedTapeServer
// for forward compatibility.
type TapeServer interface {
	// ── run lifecycle ─────────────────────────────────────────────────────────
	BeginRun(context.Context, *BeginRunRequest) (*BeginRunResponse, error)
	ResumeRun(context.Context, *ResumeRunRequest) (*ResumeRunResponse, error)
	EndRun(context.Context, *EndRunRequest) (*EndRunResponse, error)
	GetRun(context.Context, *GetRunRequest) (*RunState, error)
	ListRunsToRecover(context.Context, *ListRunsToRecoverRequest) (*ListRunsToRecoverResponse, error)
	SubscribeRun(*SubscribeRunRequest, grpc.ServerStreamingServer[JournalEntry]) error
	// ── decision ledger ───────────────────────────────────────────────────────
	RecordDecision(context.Context, *RecordDecisionRequest) (*DecisionRecord, error)
	GetDecision(context.Context, *GetDecisionRequest) (*GetDecisionResponse, error)
	// ── effect ledger ─────────────────────────────────────────────────────────
	BeginEffect(context.Context, *BeginEffectRequest) (*BeginEffectResponse, error)
	CompleteEffect(context.Context, *CompleteEffectRequest) (*EffectRecord, error)
	GetEffect(context.Context, *GetEffectRequest) (*GetEffectResponse, error)
	ReconcileEffect(context.Context, *ReconcileEffectRequest) (*EffectRecord, error)
	// ── outbox dispatch (the GCP-native hardening: for non-idempotent upstreams,
	//
	//	intent and dispatch live in separate processes; the tool body records
	//	intent, the outbox reactor dispatches via a connector, the reconciler
	//	resolves UNKNOWN ambiguity by asking the counterparty) ────────────────
	ListEffectsToDispatch(context.Context, *ListEffectsToDispatchRequest) (*ListEffectsToDispatchResponse, error)
	ClaimEffectDispatch(context.Context, *ClaimEffectDispatchRequest) (*ClaimEffectDispatchResponse, error)
	RecordDispatchAttempt(context.Context, *RecordDispatchAttemptRequest) (*EffectRecord, error)
	RecordExternalObservation(context.Context, *RecordExternalObservationRequest) (*EffectRecord, error)
	// ── obligations / compensation ────────────────────────────────────────────
	RegisterCompensation(context.Context, *RegisterCompensationRequest) (*ObligationRecord, error)
	ListObligations(context.Context, *ListObligationsRequest) (*ListObligationsResponse, error)
	ResolveObligation(context.Context, *ResolveObligationRequest) (*ObligationRecord, error)
	// The drainer surface — for the obligations reactor and operator queries.
	ListUnresolvedObligations(context.Context, *ListUnresolvedObligationsRequest) (*ListUnresolvedObligationsResponse, error)
	ClaimObligation(context.Context, *ClaimObligationRequest) (*ClaimObligationResponse, error)
	RecordObligationAttempt(context.Context, *RecordObligationAttemptRequest) (*ObligationRecord, error)
	// ── budget ────────────────────────────────────────────────────────────────
	SetBudget(context.Context, *SetBudgetRequest) (*BudgetState, error)
	AdmitBudget(context.Context, *AdmitBudgetRequest) (*AdmitBudgetResponse, error)
	ChargeBudget(context.Context, *ChargeBudgetRequest) (*BudgetState, error)
	// ── gates / signals ───────────────────────────────────────────────────────
	AwaitSignal(context.Context, *AwaitSignalRequest) (*AwaitSignalResponse, error)
	SendSignal(context.Context, *SendSignalRequest) (*SendSignalResponse, error)
	// ── reconciliation ────────────────────────────────────────────────────────
	ListPendingEffects(context.Context, *ListPendingEffectsRequest) (*ListPendingEffectsResponse, error)
	// ── timers (the delayed-reactor / gate-timeout service) ───────────────────
	SetTimer(context.Context, *SetTimerRequest) (*TimerRecord, error)
	CancelTimer(context.Context, *CancelTimerRequest) (*CancelTimerResponse, error)
	ListDueTimers(context.Context, *ListDueTimersRequest) (*ListDueTimersResponse, error)
	// ── the WAL → reactors feed (cross-run journal tail) ──────────────────────
	// The legacy cross-run journal stream; preserved for back-compat.
	// `SubscribeEventsRequest` now also accepts `from_global_seq` and
	// `subject_pattern`; pass them instead of `from_ts_ms` for new code.
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[EventEntry]) error
	// The subject-routed, global-seq-cursored bus. Path-style subjects with
	// `*` (one segment) / `**` (rest) wildcards; optional CEL predicate.
	SubscribeBySubject(*SubscribeBySubjectRequest, grpc.ServerStreamingServer[EventEntry]) error
	// ── reactions & tasks (the event-bus surface; see design-principles/tape-event-bus.md) ─
	// Reactions are server-side subscriptions: a subject pattern + optional CEL
	// predicate + a handler kind (agent | task | publish) + back-pressure config.
	// Matching journal entries become `tape_tasks` rows that dispatchers claim,
	// run, and complete/nack.
	RegisterReaction(context.Context, *Reaction) (*Reaction, error)
	DeregisterReaction(context.Context, *DeregisterReactionRequest) (*DeregisterReactionResponse, error)
	ListReactions(context.Context, *ListReactionsRequest) (*ListReactionsResponse, error)
	ClaimTasks(context.Context, *ClaimTasksRequest) (*ClaimTasksResponse, error)
	CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error)
	NackTask(context.Context, *NackTaskRequest) (*NackTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// ── reactive key-value store (the "X : X (70 → 90)" surface) ──────────────
	// Coordination through journaled state, not messages (treatise §IX ⑥).
	// Writes are atomic and versioned; WatchValue streams the current value plus
	// every change (with the prior value, so subscribers see the transition).
	WriteValue(context.Context, *WriteValueRequest) (*ValueRecord, error)
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	WatchValue(*WatchValueRequest, grpc.ServerStreamingServer[ValueEvent]) error
	DeleteValue(context.Context, *DeleteValueRequest) (*DeleteValueResponse, error)
	// ── ADK SessionService shim ───────────────────────────────────────────────
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error)
	mustEmbedUnimplementedTapeServer()
}

// UnimplementedTapeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTapeServer struct{}

func (UnimplementedTapeServer) BeginRun(context.Context, *BeginRunRequest) (*BeginRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginRun not implemented")
}
func (UnimplementedTapeServer) ResumeRun(context.Context, *ResumeRunRequest) (*ResumeRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRun not implemented")
}
func (UnimplementedTapeServer) EndRun(context.Context, *EndRunRequest) (*EndRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndRun not implemented")
}
func (UnimplementedTapeServer) GetRun(context.Context, *GetRunRequest) (*RunState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedTapeServer) ListRunsToRecover(context.Context, *ListRunsToRecoverRequest) (*ListRunsToRecoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRunsToRecover not implemented")
}
func (UnimplementedTapeServer) SubscribeRun(*SubscribeRunRequest, grpc.ServerStreamingServer[JournalEntry]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRun not implemented")
}
func (UnimplementedTapeServer) RecordDecision(context.Context, *RecordDecisionRequest) (*DecisionRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordDecision not implemented")
}
func (UnimplementedTapeServer) GetDecision(context.Context, *GetDecisionRequest) (*GetDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecision not implemented")
}
func (UnimplementedTapeServer) BeginEffect(context.Context, *BeginEffectRequest) (*BeginEffectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginEffect not implemented")
}
func (UnimplementedTapeServer) CompleteEffect(context.Context, *CompleteEffectRequest) (*EffectRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteEffect not implemented")
}
func (UnimplementedTapeServer) GetEffect(context.Context, *GetEffectRequest) (*GetEffectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEffect not implemented")
}
func (UnimplementedTapeServer) ReconcileEffect(context.Context, *ReconcileEffectRequest) (*EffectRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileEffect not implemented")
}
func (UnimplementedTapeServer) ListEffectsToDispatch(context.Context, *ListEffectsToDispatchRequest) (*ListEffectsToDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEffectsToDispatch not implemented")
}
func (UnimplementedTapeServer) ClaimEffectDispatch(context.Context, *ClaimEffectDispatchRequest) (*ClaimEffectDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimEffectDispatch not implemented")
}
func (UnimplementedTapeServer) RecordDispatchAttempt(context.Context, *RecordDispatchAttemptRequest) (*EffectRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordDispatchAttempt not implemented")
}
func (UnimplementedTapeServer) RecordExternalObservation(context.Context, *RecordExternalObservationRequest) (*EffectRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordExternalObservation not implemented")
}
func (UnimplementedTapeServer) RegisterCompensation(context.Context, *RegisterCompensationRequest) (*ObligationRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCompensation not implemented")
}
func (UnimplementedTapeServer) ListObligations(context.Context, *ListObligationsRequest) (*ListObligationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObligations not implemented")
}
func (UnimplementedTapeServer) ResolveObligation(context.Context, *ResolveObligationRequest) (*ObligationRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveObligation not implemented")
}
func (UnimplementedTapeServer) ListUnresolvedObligations(context.Context, *ListUnresolvedObligationsRequest) (*ListUnresolvedObligationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUnresolvedObligations not implemented")
}
func (UnimplementedTapeServer) ClaimObligation(context.Context, *ClaimObligationRequest) (*ClaimObligationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimObligation not implemented")
}
func (UnimplementedTapeServer) RecordObligationAttempt(context.Context, *RecordObligationAttemptRequest) (*ObligationRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordObligationAttempt not implemented")
}
func (UnimplementedTapeServer) SetBudget(context.Context, *SetBudgetRequest) (*BudgetState, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBudget not implemented")
}
func (UnimplementedTapeServer) AdmitBudget(context.Context, *AdmitBudgetRequest) (*AdmitBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitBudget not implemented")
}
func (UnimplementedTapeServer) ChargeBudget(context.Context, *ChargeBudgetRequest) (*BudgetState, error) {
	return nil, status.Error(codes.Unimplemented, "method ChargeBudget not implemented")
}
func (UnimplementedTapeServer) AwaitSignal(context.Context, *AwaitSignalRequest) (*AwaitSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AwaitSignal not implemented")
}
func (UnimplementedTapeServer) SendSignal(context.Context, *SendSignalRequest) (*SendSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSignal not implemented")
}
func (UnimplementedTapeServer) ListPendingEffects(context.Context, *ListPendingEffectsRequest) (*ListPendingEffectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingEffects not implemented")
}
func (UnimplementedTapeServer) SetTimer(context.Context, *SetTimerRequest) (*TimerRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTimer not implemented")
}
func (UnimplementedTapeServer) CancelTimer(context.Context, *CancelTimerRequest) (*CancelTimerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTimer not implemented")
}
func (UnimplementedTapeServer) ListDueTimers(context.Context, *ListDueTimersRequest) (*ListDueTimersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDueTimers not implemented")
}
func (UnimplementedTapeServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[EventEntry]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedTapeServer) SubscribeBySubject(*SubscribeBySubjectRequest, grpc.ServerStreamingServer[EventEntry]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBySubject not implemented")
}
func (UnimplementedTapeServer) RegisterReaction(context.Context, *Reaction) (*Reaction, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterReaction not implemented")
}
func (UnimplementedTapeServer) DeregisterReaction(context.Context, *DeregisterReactionRequest) (*DeregisterReactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterReaction not implemented")
}
func (UnimplementedTapeServer) ListReactions(context.Context, *ListReactionsRequest) (*ListReactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReactions not implemented")
}
func (UnimplementedTapeServer) ClaimTasks(context.Context, *ClaimTasksRequest) (*ClaimTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTasks not implemented")
}
func (UnimplementedTapeServer) CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedTapeServer) NackTask(context.Context, *NackTaskRequest) (*NackTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NackTask not implemented")
}
func (UnimplementedTapeServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTapeServer) WriteValue(context.Context, *WriteValueRequest) (*ValueRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteValue not implemented")
}
func (UnimplementedTapeServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedTapeServer) WatchValue(*WatchValueRequest, grpc.ServerStreamingServer[ValueEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchValue not implemented")
}
func (UnimplementedTapeServer) DeleteValue(context.Context, *DeleteValueRequest) (*DeleteValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteValue not implemented")
}
func (UnimplementedTapeServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedTapeServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedTapeServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedTapeServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedTapeServer) AppendEvent(context.Context, *AppendEventRequest) (*AppendEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEvent not implemented")
}
func (UnimplementedTapeServer) mustEmbedUnimplementedTapeServer() {}
func (UnimplementedTapeServer) testEmbeddedByValue()              {}

// UnsafeTapeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TapeServer will
// result in compilation errors.
type UnsafeTapeServer interface {
	mustEmbedUnimplementedTapeServer()
}

func RegisterTapeServer(s grpc.ServiceRegistrar, srv TapeServer) {
	// If the following call panics, it indicates UnimplementedTapeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tape_ServiceDesc, srv)
}

func _Tape_BeginRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).BeginRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_BeginRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).BeginRun(ctx, req.(*BeginRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ResumeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ResumeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ResumeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ResumeRun(ctx, req.(*ResumeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_EndRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).EndRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_EndRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).EndRun(ctx, req.(*EndRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListRunsToRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsToRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListRunsToRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListRunsToRecover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListRunsToRecover(ctx, req.(*ListRunsToRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_SubscribeRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TapeServer).SubscribeRun(m, &grpc.GenericServerStream[SubscribeRunRequest, JournalEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_SubscribeRunServer = grpc.ServerStreamingServer[JournalEntry]

func _Tape_RecordDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).RecordDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_RecordDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).RecordDecision(ctx, req.(*RecordDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_GetDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).GetDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_GetDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).GetDecision(ctx, req.(*GetDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_BeginEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).BeginEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_BeginEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).BeginEffect(ctx, req.(*BeginEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_CompleteEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).CompleteEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_CompleteEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).CompleteEffect(ctx, req.(*CompleteEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_GetEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).GetEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_GetEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).GetEffect(ctx, req.(*GetEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ReconcileEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ReconcileEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ReconcileEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ReconcileEffect(ctx, req.(*ReconcileEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListEffectsToDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEffectsToDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListEffectsToDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListEffectsToDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListEffectsToDispatch(ctx, req.(*ListEffectsToDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ClaimEffectDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimEffectDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ClaimEffectDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ClaimEffectDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ClaimEffectDispatch(ctx, req.(*ClaimEffectDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_RecordDispatchAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDispatchAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).RecordDispatchAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_RecordDispatchAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).RecordDispatchAttempt(ctx, req.(*RecordDispatchAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_RecordExternalObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordExternalObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).RecordExternalObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_RecordExternalObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).RecordExternalObservation(ctx, req.(*RecordExternalObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_RegisterCompensation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCompensationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).RegisterCompensation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_RegisterCompensation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).RegisterCompensation(ctx, req.(*RegisterCompensationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListObligations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObligationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListObligations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListObligations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListObligations(ctx, req.(*ListObligationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ResolveObligation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveObligationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ResolveObligation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ResolveObligation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ResolveObligation(ctx, req.(*ResolveObligationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListUnresolvedObligations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnresolvedObligationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListUnresolvedObligations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListUnresolvedObligations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListUnresolvedObligations(ctx, req.(*ListUnresolvedObligationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ClaimObligation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimObligationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ClaimObligation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ClaimObligation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ClaimObligation(ctx, req.(*ClaimObligationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_RecordObligationAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordObligationAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).RecordObligationAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_RecordObligationAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).RecordObligationAttempt(ctx, req.(*RecordObligationAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_SetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).SetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_SetBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).SetBudget(ctx, req.(*SetBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_AdmitBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).AdmitBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_AdmitBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).AdmitBudget(ctx, req.(*AdmitBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ChargeBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ChargeBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ChargeBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ChargeBudget(ctx, req.(*ChargeBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_AwaitSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwaitSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).AwaitSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_AwaitSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).AwaitSignal(ctx, req.(*AwaitSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_SendSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).SendSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_SendSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).SendSignal(ctx, req.(*SendSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListPendingEffects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingEffectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListPendingEffects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListPendingEffects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListPendingEffects(ctx, req.(*ListPendingEffectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_SetTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).SetTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_SetTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).SetTimer(ctx, req.(*SetTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_CancelTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).CancelTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_CancelTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).CancelTimer(ctx, req.(*CancelTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListDueTimers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDueTimersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListDueTimers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListDueTimers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListDueTimers(ctx, req.(*ListDueTimersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TapeServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, EventEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_SubscribeEventsServer = grpc.ServerStreamingServer[EventEntry]

func _Tape_SubscribeBySubject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeBySubjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TapeServer).SubscribeBySubject(m, &grpc.GenericServerStream[SubscribeBySubjectRequest, EventEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_SubscribeBySubjectServer = grpc.ServerStreamingServer[EventEntry]

func _Tape_RegisterReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).RegisterReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_RegisterReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).RegisterReaction(ctx, req.(*Reaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_DeregisterReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).DeregisterReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_DeregisterReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).DeregisterReaction(ctx, req.(*DeregisterReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListReactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListReactions(ctx, req.(*ListReactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ClaimTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ClaimTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ClaimTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ClaimTasks(ctx, req.(*ClaimTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_NackTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).NackTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_NackTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).NackTask(ctx, req.(*NackTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_WriteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).WriteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_WriteValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).WriteValue(ctx, req.(*WriteValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_WatchValue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchValueRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TapeServer).WatchValue(m, &grpc.GenericServerStream[WatchValueRequest, ValueEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tape_WatchValueServer = grpc.ServerStreamingServer[ValueEvent]

func _Tape_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_DeleteValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).DeleteValue(ctx, req.(*DeleteValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tape_AppendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapeServer).AppendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tape_AppendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapeServer).AppendEvent(ctx, req.(*AppendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tape_ServiceDesc is the grpc.ServiceDesc for Tape service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tape_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tape.v1.Tape",
	HandlerType: (*TapeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginRun",
			Handler:    _Tape_BeginRun_Handler,
		},
		{
			MethodName: "ResumeRun",
			Handler:    _Tape_ResumeRun_Handler,
		},
		{
			MethodName: "EndRun",
			Handler:    _Tape_EndRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _Tape_GetRun_Handler,
		},
		{
			MethodName: "ListRunsToRecover",
			Handler:    _Tape_ListRunsToRecover_Handler,
		},
		{
			MethodName: "RecordDecision",
			Handler:    _Tape_RecordDecision_Handler,
		},
		{
			MethodName: "GetDecision",
			Handler:    _Tape_GetDecision_Handler,
		},
		{
			MethodName: "BeginEffect",
			Handler:    _Tape_BeginEffect_Handler,
		},
		{
			MethodName: "CompleteEffect",
			Handler:    _Tape_CompleteEffect_Handler,
		},
		{
			MethodName: "GetEffect",
			Handler:    _Tape_GetEffect_Handler,
		},
		{
			MethodName: "ReconcileEffect",
			Handler:    _Tape_ReconcileEffect_Handler,
		},
		{
			MethodName: "ListEffectsToDispatch",
			Handler:    _Tape_ListEffectsToDispatch_Handler,
		},
		{
			MethodName: "ClaimEffectDispatch",
			Handler:    _Tape_ClaimEffectDispatch_Handler,
		},
		{
			MethodName: "RecordDispatchAttempt",
			Handler:    _Tape_RecordDispatchAttempt_Handler,
		},
		{
			MethodName: "RecordExternalObservation",
			Handler:    _Tape_RecordExternalObservation_Handler,
		},
		{
			MethodName: "RegisterCompensation",
			Handler:    _Tape_RegisterCompensation_Handler,
		},
		{
			MethodName: "ListObligations",
			Handler:    _Tape_ListObligations_Handler,
		},
		{
			MethodName: "ResolveObligation",
			Handler:    _Tape_ResolveObligation_Handler,
		},
		{
			MethodName: "ListUnresolvedObligations",
			Handler:    _Tape_ListUnresolvedObligations_Handler,
		},
		{
			MethodName: "ClaimObligation",
			Handler:    _Tape_ClaimObligation_Handler,
		},
		{
			MethodName: "RecordObligationAttempt",
			Handler:    _Tape_RecordObligationAttempt_Handler,
		},
		{
			MethodName: "SetBudget",
			Handler:    _Tape_SetBudget_Handler,
		},
		{
			MethodName: "AdmitBudget",
			Handler:    _Tape_AdmitBudget_Handler,
		},
		{
			MethodName: "ChargeBudget",
			Handler:    _Tape_ChargeBudget_Handler,
		},
		{
			MethodName: "AwaitSignal",
			Handler:    _Tape_AwaitSignal_Handler,
		},
		{
			MethodName: "SendSignal",
			Handler:    _Tape_SendSignal_Handler,
		},
		{
			MethodName: "ListPendingEffects",
			Handler:    _Tape_ListPendingEffects_Handler,
		},
		{
			MethodName: "SetTimer",
			Handler:    _Tape_SetTimer_Handler,
		},
		{
			MethodName: "CancelTimer",
			Handler:    _Tape_CancelTimer_Handler,
		},
		{
			MethodName: "ListDueTimers",
			Handler:    _Tape_ListDueTimers_Handler,
		},
		{
			MethodName: "RegisterReaction",
			Handler:    _Tape_RegisterReaction_Handler,
		},
		{
			MethodName: "DeregisterReaction",
			Handler:    _Tape_DeregisterReaction_Handler,
		},
		{
			MethodName: "ListReactions",
			Handler:    _Tape_ListReactions_Handler,
		},
		{
			MethodName: "ClaimTasks",
			Handler:    _Tape_ClaimTasks_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _Tape_CompleteTask_Handler,
		},
		{
			MethodName: "NackTask",
			Handler:    _Tape_NackTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Tape_ListTasks_Handler,
		},
		{
			MethodName: "WriteValue",
			Handler:    _Tape_WriteValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Tape_GetValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _Tape_DeleteValue_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Tape_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Tape_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Tape_ListSessions_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Tape_DeleteSession_Handler,
		},
		{
			MethodName: "AppendEvent",
			Handler:    _Tape_AppendEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRun",
			Handler:       _Tape_SubscribeRun_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _Tape_SubscribeEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBySubject",
			Handler:       _Tape_SubscribeBySubject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchValue",
			Handler:       _Tape_WatchValue_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tape.proto",
}
