# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tape_pb2 as tape__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tape_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TapeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginRun = channel.unary_unary(
                '/tape.v1.Tape/BeginRun',
                request_serializer=tape__pb2.BeginRunRequest.SerializeToString,
                response_deserializer=tape__pb2.BeginRunResponse.FromString,
                _registered_method=True)
        self.ResumeRun = channel.unary_unary(
                '/tape.v1.Tape/ResumeRun',
                request_serializer=tape__pb2.ResumeRunRequest.SerializeToString,
                response_deserializer=tape__pb2.ResumeRunResponse.FromString,
                _registered_method=True)
        self.EndRun = channel.unary_unary(
                '/tape.v1.Tape/EndRun',
                request_serializer=tape__pb2.EndRunRequest.SerializeToString,
                response_deserializer=tape__pb2.EndRunResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/tape.v1.Tape/GetRun',
                request_serializer=tape__pb2.GetRunRequest.SerializeToString,
                response_deserializer=tape__pb2.RunState.FromString,
                _registered_method=True)
        self.ListRunsToRecover = channel.unary_unary(
                '/tape.v1.Tape/ListRunsToRecover',
                request_serializer=tape__pb2.ListRunsToRecoverRequest.SerializeToString,
                response_deserializer=tape__pb2.ListRunsToRecoverResponse.FromString,
                _registered_method=True)
        self.SubscribeRun = channel.unary_stream(
                '/tape.v1.Tape/SubscribeRun',
                request_serializer=tape__pb2.SubscribeRunRequest.SerializeToString,
                response_deserializer=tape__pb2.JournalEntry.FromString,
                _registered_method=True)
        self.RecordDecision = channel.unary_unary(
                '/tape.v1.Tape/RecordDecision',
                request_serializer=tape__pb2.RecordDecisionRequest.SerializeToString,
                response_deserializer=tape__pb2.DecisionRecord.FromString,
                _registered_method=True)
        self.GetDecision = channel.unary_unary(
                '/tape.v1.Tape/GetDecision',
                request_serializer=tape__pb2.GetDecisionRequest.SerializeToString,
                response_deserializer=tape__pb2.GetDecisionResponse.FromString,
                _registered_method=True)
        self.BeginEffect = channel.unary_unary(
                '/tape.v1.Tape/BeginEffect',
                request_serializer=tape__pb2.BeginEffectRequest.SerializeToString,
                response_deserializer=tape__pb2.BeginEffectResponse.FromString,
                _registered_method=True)
        self.CompleteEffect = channel.unary_unary(
                '/tape.v1.Tape/CompleteEffect',
                request_serializer=tape__pb2.CompleteEffectRequest.SerializeToString,
                response_deserializer=tape__pb2.EffectRecord.FromString,
                _registered_method=True)
        self.GetEffect = channel.unary_unary(
                '/tape.v1.Tape/GetEffect',
                request_serializer=tape__pb2.GetEffectRequest.SerializeToString,
                response_deserializer=tape__pb2.GetEffectResponse.FromString,
                _registered_method=True)
        self.ReconcileEffect = channel.unary_unary(
                '/tape.v1.Tape/ReconcileEffect',
                request_serializer=tape__pb2.ReconcileEffectRequest.SerializeToString,
                response_deserializer=tape__pb2.EffectRecord.FromString,
                _registered_method=True)
        self.RegisterCompensation = channel.unary_unary(
                '/tape.v1.Tape/RegisterCompensation',
                request_serializer=tape__pb2.RegisterCompensationRequest.SerializeToString,
                response_deserializer=tape__pb2.ObligationRecord.FromString,
                _registered_method=True)
        self.ListObligations = channel.unary_unary(
                '/tape.v1.Tape/ListObligations',
                request_serializer=tape__pb2.ListObligationsRequest.SerializeToString,
                response_deserializer=tape__pb2.ListObligationsResponse.FromString,
                _registered_method=True)
        self.ResolveObligation = channel.unary_unary(
                '/tape.v1.Tape/ResolveObligation',
                request_serializer=tape__pb2.ResolveObligationRequest.SerializeToString,
                response_deserializer=tape__pb2.ObligationRecord.FromString,
                _registered_method=True)
        self.ListUnresolvedObligations = channel.unary_unary(
                '/tape.v1.Tape/ListUnresolvedObligations',
                request_serializer=tape__pb2.ListUnresolvedObligationsRequest.SerializeToString,
                response_deserializer=tape__pb2.ListUnresolvedObligationsResponse.FromString,
                _registered_method=True)
        self.ClaimObligation = channel.unary_unary(
                '/tape.v1.Tape/ClaimObligation',
                request_serializer=tape__pb2.ClaimObligationRequest.SerializeToString,
                response_deserializer=tape__pb2.ClaimObligationResponse.FromString,
                _registered_method=True)
        self.RecordObligationAttempt = channel.unary_unary(
                '/tape.v1.Tape/RecordObligationAttempt',
                request_serializer=tape__pb2.RecordObligationAttemptRequest.SerializeToString,
                response_deserializer=tape__pb2.ObligationRecord.FromString,
                _registered_method=True)
        self.SetBudget = channel.unary_unary(
                '/tape.v1.Tape/SetBudget',
                request_serializer=tape__pb2.SetBudgetRequest.SerializeToString,
                response_deserializer=tape__pb2.BudgetState.FromString,
                _registered_method=True)
        self.AdmitBudget = channel.unary_unary(
                '/tape.v1.Tape/AdmitBudget',
                request_serializer=tape__pb2.AdmitBudgetRequest.SerializeToString,
                response_deserializer=tape__pb2.AdmitBudgetResponse.FromString,
                _registered_method=True)
        self.ChargeBudget = channel.unary_unary(
                '/tape.v1.Tape/ChargeBudget',
                request_serializer=tape__pb2.ChargeBudgetRequest.SerializeToString,
                response_deserializer=tape__pb2.BudgetState.FromString,
                _registered_method=True)
        self.AwaitSignal = channel.unary_unary(
                '/tape.v1.Tape/AwaitSignal',
                request_serializer=tape__pb2.AwaitSignalRequest.SerializeToString,
                response_deserializer=tape__pb2.AwaitSignalResponse.FromString,
                _registered_method=True)
        self.SendSignal = channel.unary_unary(
                '/tape.v1.Tape/SendSignal',
                request_serializer=tape__pb2.SendSignalRequest.SerializeToString,
                response_deserializer=tape__pb2.SendSignalResponse.FromString,
                _registered_method=True)
        self.ListPendingEffects = channel.unary_unary(
                '/tape.v1.Tape/ListPendingEffects',
                request_serializer=tape__pb2.ListPendingEffectsRequest.SerializeToString,
                response_deserializer=tape__pb2.ListPendingEffectsResponse.FromString,
                _registered_method=True)
        self.SetTimer = channel.unary_unary(
                '/tape.v1.Tape/SetTimer',
                request_serializer=tape__pb2.SetTimerRequest.SerializeToString,
                response_deserializer=tape__pb2.TimerRecord.FromString,
                _registered_method=True)
        self.CancelTimer = channel.unary_unary(
                '/tape.v1.Tape/CancelTimer',
                request_serializer=tape__pb2.CancelTimerRequest.SerializeToString,
                response_deserializer=tape__pb2.CancelTimerResponse.FromString,
                _registered_method=True)
        self.ListDueTimers = channel.unary_unary(
                '/tape.v1.Tape/ListDueTimers',
                request_serializer=tape__pb2.ListDueTimersRequest.SerializeToString,
                response_deserializer=tape__pb2.ListDueTimersResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/tape.v1.Tape/SubscribeEvents',
                request_serializer=tape__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=tape__pb2.EventEntry.FromString,
                _registered_method=True)
        self.SubscribeBySubject = channel.unary_stream(
                '/tape.v1.Tape/SubscribeBySubject',
                request_serializer=tape__pb2.SubscribeBySubjectRequest.SerializeToString,
                response_deserializer=tape__pb2.EventEntry.FromString,
                _registered_method=True)
        self.RegisterReaction = channel.unary_unary(
                '/tape.v1.Tape/RegisterReaction',
                request_serializer=tape__pb2.Reaction.SerializeToString,
                response_deserializer=tape__pb2.Reaction.FromString,
                _registered_method=True)
        self.DeregisterReaction = channel.unary_unary(
                '/tape.v1.Tape/DeregisterReaction',
                request_serializer=tape__pb2.DeregisterReactionRequest.SerializeToString,
                response_deserializer=tape__pb2.DeregisterReactionResponse.FromString,
                _registered_method=True)
        self.ListReactions = channel.unary_unary(
                '/tape.v1.Tape/ListReactions',
                request_serializer=tape__pb2.ListReactionsRequest.SerializeToString,
                response_deserializer=tape__pb2.ListReactionsResponse.FromString,
                _registered_method=True)
        self.ClaimTasks = channel.unary_unary(
                '/tape.v1.Tape/ClaimTasks',
                request_serializer=tape__pb2.ClaimTasksRequest.SerializeToString,
                response_deserializer=tape__pb2.ClaimTasksResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/tape.v1.Tape/CompleteTask',
                request_serializer=tape__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=tape__pb2.CompleteTaskResponse.FromString,
                _registered_method=True)
        self.NackTask = channel.unary_unary(
                '/tape.v1.Tape/NackTask',
                request_serializer=tape__pb2.NackTaskRequest.SerializeToString,
                response_deserializer=tape__pb2.NackTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/tape.v1.Tape/ListTasks',
                request_serializer=tape__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=tape__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.WriteValue = channel.unary_unary(
                '/tape.v1.Tape/WriteValue',
                request_serializer=tape__pb2.WriteValueRequest.SerializeToString,
                response_deserializer=tape__pb2.ValueRecord.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/tape.v1.Tape/GetValue',
                request_serializer=tape__pb2.GetValueRequest.SerializeToString,
                response_deserializer=tape__pb2.GetValueResponse.FromString,
                _registered_method=True)
        self.WatchValue = channel.unary_stream(
                '/tape.v1.Tape/WatchValue',
                request_serializer=tape__pb2.WatchValueRequest.SerializeToString,
                response_deserializer=tape__pb2.ValueEvent.FromString,
                _registered_method=True)
        self.DeleteValue = channel.unary_unary(
                '/tape.v1.Tape/DeleteValue',
                request_serializer=tape__pb2.DeleteValueRequest.SerializeToString,
                response_deserializer=tape__pb2.DeleteValueResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/tape.v1.Tape/CreateSession',
                request_serializer=tape__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=tape__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/tape.v1.Tape/GetSession',
                request_serializer=tape__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=tape__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/tape.v1.Tape/ListSessions',
                request_serializer=tape__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=tape__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/tape.v1.Tape/DeleteSession',
                request_serializer=tape__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=tape__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.AppendEvent = channel.unary_unary(
                '/tape.v1.Tape/AppendEvent',
                request_serializer=tape__pb2.AppendEventRequest.SerializeToString,
                response_deserializer=tape__pb2.AppendEventResponse.FromString,
                _registered_method=True)


class TapeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BeginRun(self, request, context):
        """── run lifecycle ─────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunsToRecover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordDecision(self, request, context):
        """── decision ledger ───────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecision(self, request, context):
        """re-drive replay
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginEffect(self, request, context):
        """── effect ledger ─────────────────────────────────────────────────────────
        writes pending, commits, returns key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteEffect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEffect(self, request, context):
        """re-drive short-circuit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileEffect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCompensation(self, request, context):
        """── obligations / compensation ────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObligations(self, request, context):
        """LIFO, per-run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveObligation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUnresolvedObligations(self, request, context):
        """The drainer surface — for the obligations reactor and operator queries.
        cross-run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimObligation(self, request, context):
        """atomic lease
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordObligationAttempt(self, request, context):
        """failure with backoff
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBudget(self, request, context):
        """── budget ────────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdmitBudget(self, request, context):
        """refuse if over
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChargeBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitSignal(self, request, context):
        """── gates / signals ───────────────────────────────────────────────────────
        parks the run, or returns a delivered signal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSignal(self, request, context):
        """resumes a waiting run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPendingEffects(self, request, context):
        """── reconciliation ────────────────────────────────────────────────────────
        PENDING/UNKNOWN effects, for the reconciler reactor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimer(self, request, context):
        """── timers (the delayed-reactor / gate-timeout service) ───────────────────
        idempotent on (run_id, timer_id)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDueTimers(self, request, context):
        """claim=true => atomically mark fired
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """── the WAL → reactors feed (cross-run journal tail) ──────────────────────
        The legacy cross-run journal stream; preserved for back-compat.
        `SubscribeEventsRequest` now also accepts `from_global_seq` and
        `subject_pattern`; pass them instead of `from_ts_ms` for new code.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeBySubject(self, request, context):
        """The subject-routed, global-seq-cursored bus. Path-style subjects with
        `*` (one segment) / `**` (rest) wildcards; optional CEL predicate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterReaction(self, request, context):
        """── reactions & tasks (the event-bus surface; see design-principles/tape-event-bus.md) ─
        Reactions are server-side subscriptions: a subject pattern + optional CEL
        predicate + a handler kind (agent | task | publish) + back-pressure config.
        Matching journal entries become `tape_tasks` rows that dispatchers claim,
        run, and complete/nack.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NackTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteValue(self, request, context):
        """── reactive key-value store (the "X : X (70 → 90)" surface) ──────────────
        Coordination through journaled state, not messages (treatise §IX ⑥).
        Writes are atomic and versioned; WatchValue streams the current value plus
        every change (with the prior value, so subscribers see the transition).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """── ADK SessionService shim ───────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEvent(self, request, context):
        """event + state_delta + tape projections, ONE txn
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TapeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginRun': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginRun,
                    request_deserializer=tape__pb2.BeginRunRequest.FromString,
                    response_serializer=tape__pb2.BeginRunResponse.SerializeToString,
            ),
            'ResumeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRun,
                    request_deserializer=tape__pb2.ResumeRunRequest.FromString,
                    response_serializer=tape__pb2.ResumeRunResponse.SerializeToString,
            ),
            'EndRun': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRun,
                    request_deserializer=tape__pb2.EndRunRequest.FromString,
                    response_serializer=tape__pb2.EndRunResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=tape__pb2.GetRunRequest.FromString,
                    response_serializer=tape__pb2.RunState.SerializeToString,
            ),
            'ListRunsToRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunsToRecover,
                    request_deserializer=tape__pb2.ListRunsToRecoverRequest.FromString,
                    response_serializer=tape__pb2.ListRunsToRecoverResponse.SerializeToString,
            ),
            'SubscribeRun': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRun,
                    request_deserializer=tape__pb2.SubscribeRunRequest.FromString,
                    response_serializer=tape__pb2.JournalEntry.SerializeToString,
            ),
            'RecordDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordDecision,
                    request_deserializer=tape__pb2.RecordDecisionRequest.FromString,
                    response_serializer=tape__pb2.DecisionRecord.SerializeToString,
            ),
            'GetDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecision,
                    request_deserializer=tape__pb2.GetDecisionRequest.FromString,
                    response_serializer=tape__pb2.GetDecisionResponse.SerializeToString,
            ),
            'BeginEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginEffect,
                    request_deserializer=tape__pb2.BeginEffectRequest.FromString,
                    response_serializer=tape__pb2.BeginEffectResponse.SerializeToString,
            ),
            'CompleteEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteEffect,
                    request_deserializer=tape__pb2.CompleteEffectRequest.FromString,
                    response_serializer=tape__pb2.EffectRecord.SerializeToString,
            ),
            'GetEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffect,
                    request_deserializer=tape__pb2.GetEffectRequest.FromString,
                    response_serializer=tape__pb2.GetEffectResponse.SerializeToString,
            ),
            'ReconcileEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileEffect,
                    request_deserializer=tape__pb2.ReconcileEffectRequest.FromString,
                    response_serializer=tape__pb2.EffectRecord.SerializeToString,
            ),
            'RegisterCompensation': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCompensation,
                    request_deserializer=tape__pb2.RegisterCompensationRequest.FromString,
                    response_serializer=tape__pb2.ObligationRecord.SerializeToString,
            ),
            'ListObligations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObligations,
                    request_deserializer=tape__pb2.ListObligationsRequest.FromString,
                    response_serializer=tape__pb2.ListObligationsResponse.SerializeToString,
            ),
            'ResolveObligation': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveObligation,
                    request_deserializer=tape__pb2.ResolveObligationRequest.FromString,
                    response_serializer=tape__pb2.ObligationRecord.SerializeToString,
            ),
            'ListUnresolvedObligations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUnresolvedObligations,
                    request_deserializer=tape__pb2.ListUnresolvedObligationsRequest.FromString,
                    response_serializer=tape__pb2.ListUnresolvedObligationsResponse.SerializeToString,
            ),
            'ClaimObligation': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimObligation,
                    request_deserializer=tape__pb2.ClaimObligationRequest.FromString,
                    response_serializer=tape__pb2.ClaimObligationResponse.SerializeToString,
            ),
            'RecordObligationAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordObligationAttempt,
                    request_deserializer=tape__pb2.RecordObligationAttemptRequest.FromString,
                    response_serializer=tape__pb2.ObligationRecord.SerializeToString,
            ),
            'SetBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBudget,
                    request_deserializer=tape__pb2.SetBudgetRequest.FromString,
                    response_serializer=tape__pb2.BudgetState.SerializeToString,
            ),
            'AdmitBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.AdmitBudget,
                    request_deserializer=tape__pb2.AdmitBudgetRequest.FromString,
                    response_serializer=tape__pb2.AdmitBudgetResponse.SerializeToString,
            ),
            'ChargeBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.ChargeBudget,
                    request_deserializer=tape__pb2.ChargeBudgetRequest.FromString,
                    response_serializer=tape__pb2.BudgetState.SerializeToString,
            ),
            'AwaitSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.AwaitSignal,
                    request_deserializer=tape__pb2.AwaitSignalRequest.FromString,
                    response_serializer=tape__pb2.AwaitSignalResponse.SerializeToString,
            ),
            'SendSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSignal,
                    request_deserializer=tape__pb2.SendSignalRequest.FromString,
                    response_serializer=tape__pb2.SendSignalResponse.SerializeToString,
            ),
            'ListPendingEffects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPendingEffects,
                    request_deserializer=tape__pb2.ListPendingEffectsRequest.FromString,
                    response_serializer=tape__pb2.ListPendingEffectsResponse.SerializeToString,
            ),
            'SetTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimer,
                    request_deserializer=tape__pb2.SetTimerRequest.FromString,
                    response_serializer=tape__pb2.TimerRecord.SerializeToString,
            ),
            'CancelTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTimer,
                    request_deserializer=tape__pb2.CancelTimerRequest.FromString,
                    response_serializer=tape__pb2.CancelTimerResponse.SerializeToString,
            ),
            'ListDueTimers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDueTimers,
                    request_deserializer=tape__pb2.ListDueTimersRequest.FromString,
                    response_serializer=tape__pb2.ListDueTimersResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=tape__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=tape__pb2.EventEntry.SerializeToString,
            ),
            'SubscribeBySubject': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBySubject,
                    request_deserializer=tape__pb2.SubscribeBySubjectRequest.FromString,
                    response_serializer=tape__pb2.EventEntry.SerializeToString,
            ),
            'RegisterReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterReaction,
                    request_deserializer=tape__pb2.Reaction.FromString,
                    response_serializer=tape__pb2.Reaction.SerializeToString,
            ),
            'DeregisterReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterReaction,
                    request_deserializer=tape__pb2.DeregisterReactionRequest.FromString,
                    response_serializer=tape__pb2.DeregisterReactionResponse.SerializeToString,
            ),
            'ListReactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReactions,
                    request_deserializer=tape__pb2.ListReactionsRequest.FromString,
                    response_serializer=tape__pb2.ListReactionsResponse.SerializeToString,
            ),
            'ClaimTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTasks,
                    request_deserializer=tape__pb2.ClaimTasksRequest.FromString,
                    response_serializer=tape__pb2.ClaimTasksResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=tape__pb2.CompleteTaskRequest.FromString,
                    response_serializer=tape__pb2.CompleteTaskResponse.SerializeToString,
            ),
            'NackTask': grpc.unary_unary_rpc_method_handler(
                    servicer.NackTask,
                    request_deserializer=tape__pb2.NackTaskRequest.FromString,
                    response_serializer=tape__pb2.NackTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=tape__pb2.ListTasksRequest.FromString,
                    response_serializer=tape__pb2.ListTasksResponse.SerializeToString,
            ),
            'WriteValue': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteValue,
                    request_deserializer=tape__pb2.WriteValueRequest.FromString,
                    response_serializer=tape__pb2.ValueRecord.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=tape__pb2.GetValueRequest.FromString,
                    response_serializer=tape__pb2.GetValueResponse.SerializeToString,
            ),
            'WatchValue': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchValue,
                    request_deserializer=tape__pb2.WatchValueRequest.FromString,
                    response_serializer=tape__pb2.ValueEvent.SerializeToString,
            ),
            'DeleteValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteValue,
                    request_deserializer=tape__pb2.DeleteValueRequest.FromString,
                    response_serializer=tape__pb2.DeleteValueResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=tape__pb2.CreateSessionRequest.FromString,
                    response_serializer=tape__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=tape__pb2.GetSessionRequest.FromString,
                    response_serializer=tape__pb2.GetSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=tape__pb2.ListSessionsRequest.FromString,
                    response_serializer=tape__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=tape__pb2.DeleteSessionRequest.FromString,
                    response_serializer=tape__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=tape__pb2.AppendEventRequest.FromString,
                    response_serializer=tape__pb2.AppendEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tape.v1.Tape', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tape.v1.Tape', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tape(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BeginRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/BeginRun',
            tape__pb2.BeginRunRequest.SerializeToString,
            tape__pb2.BeginRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ResumeRun',
            tape__pb2.ResumeRunRequest.SerializeToString,
            tape__pb2.ResumeRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/EndRun',
            tape__pb2.EndRunRequest.SerializeToString,
            tape__pb2.EndRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/GetRun',
            tape__pb2.GetRunRequest.SerializeToString,
            tape__pb2.RunState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunsToRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListRunsToRecover',
            tape__pb2.ListRunsToRecoverRequest.SerializeToString,
            tape__pb2.ListRunsToRecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tape.v1.Tape/SubscribeRun',
            tape__pb2.SubscribeRunRequest.SerializeToString,
            tape__pb2.JournalEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/RecordDecision',
            tape__pb2.RecordDecisionRequest.SerializeToString,
            tape__pb2.DecisionRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/GetDecision',
            tape__pb2.GetDecisionRequest.SerializeToString,
            tape__pb2.GetDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/BeginEffect',
            tape__pb2.BeginEffectRequest.SerializeToString,
            tape__pb2.BeginEffectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/CompleteEffect',
            tape__pb2.CompleteEffectRequest.SerializeToString,
            tape__pb2.EffectRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/GetEffect',
            tape__pb2.GetEffectRequest.SerializeToString,
            tape__pb2.GetEffectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ReconcileEffect',
            tape__pb2.ReconcileEffectRequest.SerializeToString,
            tape__pb2.EffectRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCompensation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/RegisterCompensation',
            tape__pb2.RegisterCompensationRequest.SerializeToString,
            tape__pb2.ObligationRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObligations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListObligations',
            tape__pb2.ListObligationsRequest.SerializeToString,
            tape__pb2.ListObligationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveObligation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ResolveObligation',
            tape__pb2.ResolveObligationRequest.SerializeToString,
            tape__pb2.ObligationRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUnresolvedObligations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListUnresolvedObligations',
            tape__pb2.ListUnresolvedObligationsRequest.SerializeToString,
            tape__pb2.ListUnresolvedObligationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimObligation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ClaimObligation',
            tape__pb2.ClaimObligationRequest.SerializeToString,
            tape__pb2.ClaimObligationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordObligationAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/RecordObligationAttempt',
            tape__pb2.RecordObligationAttemptRequest.SerializeToString,
            tape__pb2.ObligationRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/SetBudget',
            tape__pb2.SetBudgetRequest.SerializeToString,
            tape__pb2.BudgetState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdmitBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/AdmitBudget',
            tape__pb2.AdmitBudgetRequest.SerializeToString,
            tape__pb2.AdmitBudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChargeBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ChargeBudget',
            tape__pb2.ChargeBudgetRequest.SerializeToString,
            tape__pb2.BudgetState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AwaitSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/AwaitSignal',
            tape__pb2.AwaitSignalRequest.SerializeToString,
            tape__pb2.AwaitSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/SendSignal',
            tape__pb2.SendSignalRequest.SerializeToString,
            tape__pb2.SendSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPendingEffects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListPendingEffects',
            tape__pb2.ListPendingEffectsRequest.SerializeToString,
            tape__pb2.ListPendingEffectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/SetTimer',
            tape__pb2.SetTimerRequest.SerializeToString,
            tape__pb2.TimerRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/CancelTimer',
            tape__pb2.CancelTimerRequest.SerializeToString,
            tape__pb2.CancelTimerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDueTimers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListDueTimers',
            tape__pb2.ListDueTimersRequest.SerializeToString,
            tape__pb2.ListDueTimersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tape.v1.Tape/SubscribeEvents',
            tape__pb2.SubscribeEventsRequest.SerializeToString,
            tape__pb2.EventEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeBySubject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tape.v1.Tape/SubscribeBySubject',
            tape__pb2.SubscribeBySubjectRequest.SerializeToString,
            tape__pb2.EventEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/RegisterReaction',
            tape__pb2.Reaction.SerializeToString,
            tape__pb2.Reaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/DeregisterReaction',
            tape__pb2.DeregisterReactionRequest.SerializeToString,
            tape__pb2.DeregisterReactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListReactions',
            tape__pb2.ListReactionsRequest.SerializeToString,
            tape__pb2.ListReactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ClaimTasks',
            tape__pb2.ClaimTasksRequest.SerializeToString,
            tape__pb2.ClaimTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/CompleteTask',
            tape__pb2.CompleteTaskRequest.SerializeToString,
            tape__pb2.CompleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NackTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/NackTask',
            tape__pb2.NackTaskRequest.SerializeToString,
            tape__pb2.NackTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListTasks',
            tape__pb2.ListTasksRequest.SerializeToString,
            tape__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/WriteValue',
            tape__pb2.WriteValueRequest.SerializeToString,
            tape__pb2.ValueRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/GetValue',
            tape__pb2.GetValueRequest.SerializeToString,
            tape__pb2.GetValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tape.v1.Tape/WatchValue',
            tape__pb2.WatchValueRequest.SerializeToString,
            tape__pb2.ValueEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/DeleteValue',
            tape__pb2.DeleteValueRequest.SerializeToString,
            tape__pb2.DeleteValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/CreateSession',
            tape__pb2.CreateSessionRequest.SerializeToString,
            tape__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/GetSession',
            tape__pb2.GetSessionRequest.SerializeToString,
            tape__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/ListSessions',
            tape__pb2.ListSessionsRequest.SerializeToString,
            tape__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/DeleteSession',
            tape__pb2.DeleteSessionRequest.SerializeToString,
            tape__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tape.v1.Tape/AppendEvent',
            tape__pb2.AppendEventRequest.SerializeToString,
            tape__pb2.AppendEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
