"""IaC generation — render Terraform from `tape.yaml`.

The CLI does NOT hide the generated IaC. It writes to `./deploy/gcp/terraform/`
inside the project, where the user can inspect, edit, and commit it. `--apply`
runs `tofu` if present, else `terraform`.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Optional

from rich.console import Console

from .config import TapeProject
from .util import ok, warn, info, run_cmd, which, fail

console = Console()

# The shipped modules live in tape/deploy/gcp/terraform/modules. The CLI emits
# a thin root module that wires the chosen subset of them. We resolve the
# packaged path at runtime.

PACKAGE_TF_ROOT = Path(__file__).resolve().parent.parent.parent / "deploy" / "gcp" / "terraform"


def runtime_modules_dir() -> Path:
    """Where the source Terraform modules live in the repo.

    For an installed copy of the CLI, the modules live alongside the SDK; we
    resolve relative to the CLI package. If the modules can't be found (e.g.
    user copied just the CLI), we fall back to fetching from the project's
    own `deploy/gcp/terraform/` if present.
    """
    if PACKAGE_TF_ROOT.exists():
        return PACKAGE_TF_ROOT
    return Path.cwd() / "deploy" / "gcp" / "terraform"


def generate(project: TapeProject, out_dir: Path) -> Path:
    """Render the root Terraform module + tfvars to `out_dir`.

    Returns the path to the written root directory.
    """
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Copy the shared module library next to the root so paths are simple.
    src_modules = runtime_modules_dir() / "modules"
    dst_modules = out_dir / "modules"
    if src_modules.exists():
        if dst_modules.exists():
            shutil.rmtree(dst_modules)
        shutil.copytree(src_modules, dst_modules)

    main_tf = _render_main_tf(project)
    vars_tf = _render_variables_tf()
    tfvars = _render_tfvars(project)

    (out_dir / "main.tf").write_text(main_tf)
    (out_dir / "variables.tf").write_text(vars_tf)
    (out_dir / "terraform.tfvars.json").write_text(json.dumps(tfvars, indent=2))
    (out_dir / "versions.tf").write_text(_RENDER_VERSIONS_TF)
    (out_dir / "README.md").write_text(_README_MD.format(project=project.project.name))
    return out_dir


def apply(root: Path, *, dry_run: bool = True) -> int:
    """Run `tofu init` + `tofu plan` (or `tofu apply` when not dry-run).

    Falls back to `terraform` when `tofu` isn't installed.
    """
    tool = which("tofu") or which("terraform")
    if not tool:
        fail("Neither `tofu` nor `terraform` is installed.",
             hint="https://opentofu.org/docs/intro/install/ or https://developer.hashicorp.com/terraform/install")
        return 2
    info(f"Using {tool}")
    rc = run_cmd([tool, "init", "-input=false"], cwd=root, check=False).returncode
    if rc != 0:
        return rc
    if dry_run:
        return run_cmd([tool, "plan", "-input=false", "-var-file=terraform.tfvars.json"],
                       cwd=root, check=False).returncode
    return run_cmd([tool, "apply", "-input=false", "-auto-approve",
                    "-var-file=terraform.tfvars.json"],
                   cwd=root, check=False).returncode


# ── module wiring ───────────────────────────────────────────────────────────

_STORE_MODULES = {
    "alloydb": "alloydb",
    "postgres": "postgres-cloudsql",
    "spanner": "spanner",
    "bigtable": "bigtable",
}

_RENDER_VERSIONS_TF = """terraform {
  required_version = ">= 1.6.0"
  required_providers {
    google      = { source = "hashicorp/google", version = ">= 5.10" }
    google-beta = { source = "hashicorp/google-beta", version = ">= 5.10" }
  }
}
"""

_README_MD = """# Terraform — {project}

Generated by `tape provision gcp`. Treat this directory as **your** infrastructure
code: commit it, code-review it, and edit it if you need to.

To plan and apply manually:

```bash
tofu init                # or: terraform init
tofu plan  -var-file=terraform.tfvars.json
tofu apply -var-file=terraform.tfvars.json
```

To regenerate after editing `tape.yaml`:

```bash
tape provision gcp --dry-run     # re-render only
tape provision gcp --apply       # re-render and apply
```
"""


def _render_main_tf(p: TapeProject) -> str:
    store_module = _STORE_MODULES.get(p.tape.store.kind)
    sections: list[str] = [
        'provider "google" {',
        '  project = var.project_id',
        '  region  = var.region',
        '}',
        'provider "google-beta" {',
        '  project = var.project_id',
        '  region  = var.region',
        '}',
        "",
        'module "artifact_registry" {',
        '  source     = "./modules/artifact-registry"',
        '  project_id = var.project_id',
        '  region     = var.region',
        '  repository = var.artifact_registry_repository',
        "}",
        "",
        'module "iam" {',
        '  source                  = "./modules/iam"',
        '  project_id              = var.project_id',
        '  service_account_prefix  = var.service_account_prefix',
        "}",
        "",
        'module "secrets" {',
        '  source     = "./modules/secret-manager"',
        '  project_id = var.project_id',
        '  region     = var.region',
        '  secrets    = var.secrets',
        "}",
        "",
    ]

    if store_module:
        sections.append(f'module "store" {{')
        sections.append(f'  source     = "./modules/{store_module}"')
        sections.append('  project_id = var.project_id')
        sections.append('  region     = var.region')
        sections.append('  instance_name = var.store_instance_name')
        sections.append('  database_name = var.store_database_name')
        sections.append("}")
        sections.append("")

    if p.tape.events.kind == "pubsub":
        sections.append('module "events" {')
        sections.append('  source        = "./modules/pubsub"')
        sections.append('  project_id    = var.project_id')
        sections.append('  topic         = var.events_topic')
        sections.append('  outbox_topic  = var.events_outbox_topic')
        sections.append('  dlq_topic     = var.events_dlq_topic')
        sections.append("}")
        sections.append("")

    if p.tape.server.target == "cloud_run":
        sections.append('module "tape_server" {')
        sections.append('  source                 = "./modules/tape-cloud-run"')
        sections.append('  project_id             = var.project_id')
        sections.append('  region                 = var.region')
        sections.append('  image                  = var.tape_server_image')
        sections.append('  service_account_email  = module.iam.tape_server_sa_email')
        sections.append('  store_url_secret       = var.store_url_secret')
        sections.append('  min_instances          = var.tape_server_min_instances')
        sections.append('  max_instances          = var.tape_server_max_instances')
        sections.append('  cpu                    = var.tape_server_cpu')
        sections.append('  memory                 = var.tape_server_memory')
        sections.append('  ingress                = var.tape_server_ingress')
        sections.append('  vpc_connector          = var.vpc_connector')
        sections.append("}")
        sections.append("")
        sections.append('module "tape_reactors" {')
        sections.append('  source                 = "./modules/tape-reactors-cloud-run"')
        sections.append('  project_id             = var.project_id')
        sections.append('  region                 = var.region')
        sections.append('  tape_server_url        = module.tape_server.url')
        sections.append('  service_account_email  = module.iam.tape_reactor_sa_email')
        sections.append(f'  reactors               = {json.dumps(p.tape.reactors.enabled_names())}')
        sections.append("}")
        sections.append("")
    elif p.tape.server.target == "gke":
        sections.append('module "tape_gke" {')
        sections.append('  source     = "./modules/tape-gke"')
        sections.append('  project_id = var.project_id')
        sections.append('  region     = var.region')
        sections.append('  cluster    = var.gke_cluster')
        sections.append("}")
        sections.append("")

    sections.append('module "observability" {')
    sections.append('  source     = "./modules/observability"')
    sections.append('  project_id = var.project_id')
    sections.append('  region     = var.region')
    sections.append('  service_name = "tape-server"')
    sections.append("}")
    sections.append("")

    sections.append('output "tape_server_url" {')
    sections.append('  value       = try(module.tape_server.url, "")')
    sections.append('  description = "The Cloud Run URL of the Tape server (empty for non-Cloud Run targets)."')
    sections.append("}")
    return "\n".join(sections) + "\n"


def _render_variables_tf() -> str:
    items = [
        ("project_id", "string", None),
        ("region", "string", '"us-central1"'),
        ("artifact_registry_repository", "string", '"tape"'),
        ("service_account_prefix", "string", '"tape"'),
        ("secrets", "map(string)", "{}"),
        ("store_instance_name", "string", '"tape"'),
        ("store_database_name", "string", '"tape"'),
        ("store_url_secret", "string", '"TAPE_STORE_URL"'),
        ("events_topic", "string", '"tape-events"'),
        ("events_outbox_topic", "string", '"tape-outbox"'),
        ("events_dlq_topic", "string", '"tape-dlq"'),
        ("tape_server_image", "string", None),
        ("tape_server_min_instances", "number", "0"),
        ("tape_server_max_instances", "number", "10"),
        ("tape_server_cpu", "string", '"1"'),
        ("tape_server_memory", "string", '"512Mi"'),
        ("tape_server_ingress", "string", '"internal"'),
        ("vpc_connector", "string", '""'),
        ("gke_cluster", "string", '""'),
    ]
    out: list[str] = []
    for name, typ, default in items:
        out.append(f'variable "{name}" {{')
        out.append(f'  type    = {typ}')
        if default is not None:
            out.append(f'  default = {default}')
        out.append("}")
    return "\n".join(out) + "\n"


def _render_tfvars(p: TapeProject) -> dict:
    return {
        "project_id": p.gcp.project_id or "<set GOOGLE_CLOUD_PROJECT>",
        "region": p.gcp.region,
        "artifact_registry_repository": p.gcp.artifact_registry_repository,
        "service_account_prefix": p.gcp.service_account_prefix,
        "store_instance_name": p.project.name,
        "store_database_name": p.project.name,
        "store_url_secret": p.tape.store.url_secret or "TAPE_STORE_URL",
        "events_topic": p.tape.events.topic,
        "events_outbox_topic": p.tape.events.outbox_topic or f"{p.tape.events.topic}-outbox",
        "events_dlq_topic": p.tape.events.dlq_topic or f"{p.tape.events.topic}-dlq",
        "tape_server_image": p.tape.server.image,
        "tape_server_min_instances": p.tape.server.min_instances,
        "tape_server_max_instances": p.tape.server.max_instances,
        "tape_server_cpu": p.tape.server.cpu,
        "tape_server_memory": p.tape.server.memory,
        "tape_server_ingress": p.tape.server.ingress,
        "vpc_connector": p.gcp.network.vpc_connector or "",
    }


__all__ = ["generate", "apply", "runtime_modules_dir"]
