"""Non-invasive Tape wiring for an existing ADK project.

If you already have a `Runner` factory of your own, you have two options:

  1. Replace the body of your factory with a call to `durable_app(...)`.
  2. Wrap your existing factory with `build_durable_runner(root_agent=...)`
     below, which adds the `TapePlugin` and `TapeSessionService` and returns
     the `(App, Runner)` pair without touching your tool bodies.

This file was generated by `tape enhance`. Edit freely.
"""

from __future__ import annotations

import tape
from tape.adk import durable_app


def build_durable_runner(*, root_agent, name: str = "{{ name }}",
                         budget: tape.Budget | None = None):
    return durable_app(
        name=name,
        agent=root_agent,
        budget=budget or tape.Budget(usd_cap=50, token_cap=2_000_000),
    )
